/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String sendRequest(String uriString) throws Exception {
        
        HttpClient client = HttpClient.newHttpClient();
        
        HttpRequest request = HttpRequest.newBuilder()
            .uri(new URI(uriString))
            .GET()
            .build();

        HttpResponse<String> response = 
            client.send(request, HttpResponse.BodyHandlers.ofString());
        
        return response.body();

    }

    public static void main(String[] args) {
        App app = new App();
        String uriString = "https://google.com/";

        try {
            System.out.println(app.sendRequest(uriString));
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
}
